create table accounts (
                         id integer generated by default as identity,
                         balance decimal (19,2),
                         version integer not null default 0,
                         customer_id integer not null,
                         primary key (id)
);
create table cards (
                      id integer generated by default as identity,
                      is_activated boolean not null,
                      number_card varchar(255),
                      version integer not null default 0,
                      account_id integer not null,
                      primary key (id)
);
create table customers (
                          id integer generated by default as identity,
                          first_name varchar(255) not null,
                          last_name varchar(255) not null,
                          passport varchar(255) not null,
                          phone varchar(255) not null,
                          version integer not null default 0,
                          primary key (id)
);

create index IdxCustomerId on accounts (customer_id);
create index IdxAccountId on cards (account_id);
alter table customers
    add constraint UniquePhone unique (phone);
alter table customers
    add constraint UniquePassport unique (passport);
alter table accounts
    add constraint FKForAccount
        foreign key (customer_id)
            references customers;
alter table cards
    add constraint FK8ForCard
        foreign key (account_id)
            references accounts;